/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HostIdRouteImport } from './routes/host.$id'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as SettingsProRouteImport } from './routes/settings_.pro'
import { Route as SettingsShortcutsRouteImport } from './routes/settings_.shortcuts'
import { Route as SettingsWatchRouteImport } from './routes/settings_.watch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIdRoute = HostIdRouteImport.update({
  id: '/host/$id',
  path: '/host/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProRoute = SettingsProRouteImport.update({
  id: '/settings_/pro',
  path: '/settings/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/settings_/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWatchRoute = SettingsWatchRouteImport.update({
  id: '/settings_/watch',
  path: '/settings/watch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/host/$id': typeof HostIdRoute
  '/session/$id': typeof SessionIdRoute
  '/settings/pro': typeof SettingsProRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/watch': typeof SettingsWatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/host/$id': typeof HostIdRoute
  '/session/$id': typeof SessionIdRoute
  '/settings/pro': typeof SettingsProRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/watch': typeof SettingsWatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/host/$id': typeof HostIdRoute
  '/session/$id': typeof SessionIdRoute
  '/settings_/pro': typeof SettingsProRoute
  '/settings_/shortcuts': typeof SettingsShortcutsRoute
  '/settings_/watch': typeof SettingsWatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/inbox'
    | '/settings'
    | '/host/$id'
    | '/session/$id'
    | '/settings/pro'
    | '/settings/shortcuts'
    | '/settings/watch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/inbox'
    | '/settings'
    | '/host/$id'
    | '/session/$id'
    | '/settings/pro'
    | '/settings/shortcuts'
    | '/settings/watch'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/inbox'
    | '/settings'
    | '/host/$id'
    | '/session/$id'
    | '/settings_/pro'
    | '/settings_/shortcuts'
    | '/settings_/watch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  InboxRoute: typeof InboxRoute
  SettingsRoute: typeof SettingsRoute
  HostIdRoute: typeof HostIdRoute
  SessionIdRoute: typeof SessionIdRoute
  SettingsProRoute: typeof SettingsProRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  SettingsWatchRoute: typeof SettingsWatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$id': {
      id: '/host/$id'
      path: '/host/$id'
      fullPath: '/host/$id'
      preLoaderRoute: typeof HostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/pro': {
      id: '/settings_/pro'
      path: '/settings/pro'
      fullPath: '/settings/pro'
      preLoaderRoute: typeof SettingsProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/shortcuts': {
      id: '/settings_/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/watch': {
      id: '/settings_/watch'
      path: '/settings/watch'
      fullPath: '/settings/watch'
      preLoaderRoute: typeof SettingsWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  InboxRoute: InboxRoute,
  SettingsRoute: SettingsRoute,
  HostIdRoute: HostIdRoute,
  SessionIdRoute: SessionIdRoute,
  SettingsProRoute: SettingsProRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsWatchRoute: SettingsWatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
